package com.zarterstein.ansifansi;

/**
 * Ansi: a lightweight ANSI control code helper.
 *
 * <p>This is a simpler version of the Fansi API, with fewer options and a
 * minimal API surface for speed. It provides direct conversion of strings to
 * ANSI colored and bold-formatted equivalents and always resets style at the
 * end of each invocation.</p>
 * 
 * <p>AI usage policy: Java is human-written, but JavaDoc is generated by AI.</p>
 *
 * <p>Design goals:
 * <ul>
 *   <li>Easy to use with one static call per formatting style</li>
 *   <li>No runtime dependencies beyond core Java</li>
 *   <li>Fast path for string wrapping</li>
 * </ul>
 * </p>
 *
 * <p>Usage example:
 * <pre>
 *   String red = Ansi.red("Warning");
 *   String boldBlue = Ansi.bBlue("Info");
 * </pre>
 * </p>
 */

public class Ansi {
    public static final String RESET = "\u001B[0m";
    public static final String BLACK = "\u001B[30m";
    public static final String WHITE = "\u001B[37m";
    public static final String BLUE = "\u001B[34m";
    public static final String RED = "\u001B[31m";
    public static final String GREEN = "\u001B[32m";
    public static final String YELLOW = "\u001B[33m";
    public static final String PURPLE = "\u001B[35m";
    public static final String CYAN = "\u001B[36m";
    public static final String BOLD = "\033[0;1m";
    public static final String NL = System.lineSeparator();

    /**
     * Wraps the input text in bold ANSI control codes and reset.
     *
     * @param str the text to format
     * @return the formatted text with ANSI bold
     */
    public static String bold ( String str ) {
        return BOLD + str + RESET;
    }

    /**
     * Wraps the input text in ANSI black foreground and reset.
     *
     * @param str the text to format
     * @return the formatted text in black
     */
    public static String black ( String str ) {
        return BLACK + str + RESET;
    }

    /**
     * Wraps the input text in ANSI white foreground and reset.
     *
     * @param str the text to format
     * @return the formatted text in white
     */
    public static String white ( String str ) {
        return WHITE + str + RESET;
    }
    /**
     * Wraps the input text in ANSI blue foreground and reset.
     *
     * @param str the text to format
     * @return the formatted text in blue
     */
    public static String blue ( String str) {
        return BLUE + str + RESET;
    }

    /**
     * Wraps the input text in ANSI red foreground and reset.
     *
     * @param str the text to format
     * @return the formatted text in red
     */
    public static String red ( String str ) {
        return RED + str + RESET;
    }

    /**
     * Wraps the input text in ANSI green foreground and reset.
     *
     * @param str the text to format
     * @return the formatted text in green
     */
    public static String green ( String str) {
        return GREEN + str + RESET;
    }

    /**
     * Wraps the input text in ANSI yellow foreground and reset.
     *
     * @param str the text to format
     * @return the formatted text in yellow
     */
    public static String yellow ( String str) {
        return YELLOW + str + RESET;
    }

    /**
     * Wraps the input text in ANSI purple foreground and reset.
     *
     * @param str the text to format
     * @return the formatted text in purple
     */
    public static String purple ( String str) {
        return PURPLE + str + RESET;
    }

    /**
     * Wraps the input text in ANSI cyan foreground and reset.
     *
     * @param str the text to format
     * @return the formatted text in cyan
     */
    public static String cyan ( String str) {
        return CYAN + str + RESET;
    }

    /**
     * Wraps the input text in ANSI bold black and reset.
     *
     * @param str the text to format
     * @return the formatted text in bold black
     */
    public static String bBlack ( String str ) {
        return BOLD + BLACK + str + RESET;
    }

    /**
     * Wraps the input text in ANSI bold white and reset.
     *
     * @param str the text to format
     * @return the formatted text in bold white
     */
    public static String bWhite ( String str ) {
        return BOLD + WHITE + str + RESET;
    }

    /**
     * Wraps the input text in ANSI bold blue and reset.
     *
     * @param str the text to format
     * @return the formatted text in bold blue
     */
    public static String bBlue ( String str) {
        return BOLD + BLUE + str + RESET;
    }

    /**
     * Wraps the input text in ANSI bold red and reset.
     *
     * @param str the text to format
     * @return the formatted text in bold red
     */
    public static String bRed ( String str ) {
        return BOLD + RED + str + RESET;
    }

    /**
     * Wraps the input text in ANSI bold green and reset.
     *
     * @param str the text to format
     * @return the formatted text in bold green
     */
    public static String bGreen ( String str) {
        return BOLD + GREEN + str + RESET;
    }

    /**
     * Wraps the input text in ANSI bold yellow and reset.
     *
     * @param str the text to format
     * @return the formatted text in bold yellow
     */
    public static String bYellow ( String str) {
        return BOLD + YELLOW + str + RESET;
    }

    /**
     * Wraps the input text in ANSI bold purple and reset.
     *
     * @param str the text to format
     * @return the formatted text in bold purple
     */
    public static String bPurple ( String str) {
        return BOLD + PURPLE + str + RESET;
    }

    /**
     * Wraps the input text in ANSI bold cyan and reset.
     *
     * @param str the text to format
     * @return the formatted text in bold cyan
     */
    public static String bCyan ( String str) {
        return BOLD + CYAN + str + RESET;
    }
}